export const COLOR_PALETTE = {
  base: {
    green: '#16A34A',
    yellow: '#FACC15',
    pink: '#EC4899',
    red: '#DC2626',
    black: '#0A0A0A',
    white: '#FFFFFF',
  },
  light: {
    green: '#15803D',
    yellow: '#CA8A04',
    pink: '#DB2777',
    red: '#B91C1C',
    background: '#FFFFFF',
    surface: '#F8FAFC',
    raisedSurface: '#F1F5F9',
    text: '#0A0A0A',
    mutedText: '#4B5563',
    border: '#E5E7EB',
  },
  dark: {
    green: '#4ADE80',
    yellow: '#FDE047',
    pink: '#F472B6',
    red: '#F87171',
    background: '#050505',
    surface: '#111827',
    raisedSurface: '#1F2937',
    text: '#F8FAFC',
    mutedText: '#CBD5E1',
    border: '#374151',
  },
  usage: {
    backgrounds: 'Use white/light gray in light mode and black/charcoal in dark mode.',
    text: 'Use neutral text for reading; reserve colored text for labels, states, and short emphasis.',
    primaryActions: 'Use green for primary buttons, active states, focus rings, and success.',
    highlights: 'Use yellow for warnings, progress highlights, badges, and celebratory details.',
    secondaryAccents: 'Use pink for secondary CTAs, info states, selected tags, and playful emphasis.',
    danger: 'Use red only for destructive actions, errors, overdue states, and critical alerts.',
    interactive: 'Use tinted fills, borders, and hover rings from the active mode color set.',
  },
  rationale:
    'The palette keeps hierarchy accessible by separating neutral structure from semantic accents. Dark mode uses brighter accent tints on black surfaces, while light mode uses deeper accent shades on white surfaces for stronger text and control contrast.',
  avoid: [
    'Do not use violet or purple shades.',
    'Avoid yellow text on white or pale gray surfaces.',
    'Avoid white text on yellow buttons or badges.',
    'Avoid red text on black unless using the lighter dark-mode red.',
    'Avoid placing red and pink adjacent for different meanings.',
    'Avoid green text on red or red text on green.',
    'Avoid using every accent at equal intensity in the same view.',
  ],
} as const;

